name: CI

on:
  push:
    branches:
      - master

env:
  DOCKER_REPO: docker.pkg.github.com/chiel/site


jobs:
  docker-lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://hadolint/hadolint:latest-debian
        with:
          entrypoint: hadolint
          args: Dockerfile

  docker-build:
    name: Build Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build the image
        env:
          DOCKER_BUILDKIT: 1
        run: docker build -t $DOCKER_REPO/site:$GITHUB_SHA .
      - name: Login to GPR
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | \
          docker login docker.pkg.github.com \
            -u "${{ secrets.REGISTRY_USER }}" \
            --password-stdin
      - name: Push image to GPR
        run: docker push $DOCKER_REPO/site:$GITHUB_SHA

  kubernetes-deploy:
    name: Deploy to kubernetes
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - uses: actions/checkout@master
      - name: Generate kubernetes config
        run: envsubst < .k8s.template.yaml > .k8s.yaml
      - name: Save DigitalOcean kubeconfig
        uses: digitalocean/action-doctl@master
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
        with:
          args: kubernetes cluster kubeconfig show primary > .kubeconfig
      - name: Apply kubernetes config
        uses: docker://lachlanevenson/k8s-kubectl
        with:
          args: --kubeconfig=.kubeconfig apply -f .k8s.yaml
